#!/bin/sh

unset DEBUG
#Uncomment the following line to get debuging ouput
#DEBUG="TRUE"
unset MAIL
#Uncomment the following line to get a Mail on error
#MAIL=mig@aon.at

usage ()
{
    echo "This is my standard Backup rotate script"
    echo ""
    echo "./rotate_backups.sh"
    echo "\t-h|--help"
    echo "\t-d|--dest=<Destination Directory>"
    echo "\t-s|--source=<Source Directory>"
    echo "\t-f|--filename=<Filename or '*'>"
    echo ""
}

debugecho ()
{ if [ ! -z "$DEBUG" ]; then echo "$*"; fi }

while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    #VALUE=`echo $1 | sed 's/^[^=]*=//g'`
    VALUE=`echo $1 | awk -F= '{print $2}'`
    case $PARAM in
        -h | --help)
            usage 
            exit 0
            ;;
        -d | --dest)
            DEST=$VALUE
            ;;
        # Source folder where files are dumped
        -s | --source)
            SRC=$VALUE
            ;;
        # Source filename (can be wildcarded)
        -f | --filename)
            FILENAME=$VALUE
            ;;        
            
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift 
done

debugecho "Source is $SRC";
debugecho "Destination is $DEST";
debugecho "Filename is $FILENAME";


if [ ! -d ${DEST} ] ; then
    mkdir ${DEST}
fi
if [ ! -d ${DEST}/backup.monthly ]; then
    mkdir ${DEST}/backup.monthly
fi
if [ ! -d ${DEST}/backup.weekly ]; then
    mkdir ${DEST}/backup.weekly
fi
if [ ! -d ${DEST}/backup.daily ]; then
    mkdir ${DEST}/backup.daily
fi



# Get current month and week day number
month_day=`date +"%d"`
week_day=`date +"%u"`

if [ ! -z "$MAIL" ]; then
# Optional check if source files exist. Email if failed.
    if [ ! -f ${SRC}/${FILENAME} ]; then
        ls -l ${SRC}/ | mail $MAIL -s "[backup script] Daily backup failed! Please check for missing files."
    fi
fi

if [ ! -f ${SRC}/${FILENAME} ]; then
   debugecho "Daily backup failed! Please check for missing files."
fi

# It is logical to run this script daily. We take files from source folder and move them to
# appropriate destination folder

# On first month day do
if [ "$month_day" -eq 1 ]; then
    DESTDIR=${DEST}/backup.monthly/
else
  # On saturdays do
    if [ "$week_day" -eq 6 ]; then
        DESTDIR=${DEST}/backup.weekly/
    else
    # On any regular day do
        DESTDIR=${DEST}/backup.daily/
    fi
fi

# Move the files
cp ${SRC}/$FILENAME ${DESTDIR}

# daily - keep for 30 days
find ${DEST}/backup.daily/ -maxdepth 1 -mtime +30 -type d -exec rm -rv {} \;

# weekly - keep for 90 days
find $DEST/backup.weekly/ -maxdepth 1 -mtime +90 -type d -exec rm -rv {} \;

# monthly - keep for 365 days
find ${DEST}/backup.monthly/ -maxdepth 1 -mtime +365 -type d -exec rm -rv {} \;

